/** 무한 스크롤 개수 */
export const itemNumber = 20;
/** 통신 주소 */
export const URL = '~~~~';

export const statementOfFinancialArray = [
  { type_nm: '유동자산', type: 'bs_current_assets', id: '1', fontWeight: 700, align: 'left'},
  { type_nm: '매출채권', type: 'bs_accounts_receivable', id: '2', fontWeight: 500, align: 'right'},
  { type_nm: '재고자산', type: 'bs_inventories', id: '3', fontWeight: 500, align: 'right'},
  { type_nm: '비유동자산', type: 'bs_non_current_assets', id: '4', fontWeight: 700, align: 'left'},
  { type_nm: '유형자산', type: 'bs_property_plant_equipment', id: '5', fontWeight: 500, align: 'right'},
  { type_nm: '무형자산', type: 'bs_intangible_assets', id: '6', fontWeight: 500, align: 'right'},
  { type_nm: '투자부동산', type: 'bs_investment_property', id: '7', fontWeight: 500, align: 'right'},
  { type_nm: '자회사 투자자산', type: 'bs_investment_subsidiary', id: '8', fontWeight: 500, align: 'right'},
  { type_nm: '자산 총계', type: 'bs_total_assets', id: '9', fontWeight: 700, align: 'left'},
  { type_nm: '유동부채', type: 'bs_current_liabilities', id: '10', fontWeight: 500, align: 'center'},
  { type_nm: '매입채무', type: 'bs_accounts_payables', id: '11', fontWeight: 500, align: 'right'},
  { type_nm: '비유동부채', type: 'bs_non_current_liabilities', id: '12', fontWeight: 500, align: 'center'},
  { type_nm: '부채총계', type: 'bs_total_liabilities', id: '13', fontWeight: 700, align: 'left'},
  { type_nm: '자본 총계', type: 'bs_total_equity', id: '14', fontWeight: 700, align: 'left'},
  { type_nm: '외부주주지분', type: 'bs_non_controlling_equity', id: '15', fontWeight: 500, align: 'center'},
  { type_nm: '지배주주 지분', type: 'bs_controlling_equity', id: '16', fontWeight: 700, align: 'center'},
  { type_nm: '유동금융자산', type: 'bs_current_financial_assets', id: '17', fontWeight: 700, align: 'left'},
  { type_nm: '현금성자산', type: 'bs_cash_and_equivalent', id: '18', fontWeight: 500, align: 'right'},
  { type_nm: '기타 단기금융상품', type: 'bs_other_current_finaicial_assets', id: '19', fontWeight: 500, align: 'right'},
  { type_nm: '비유동금융자산', type: 'bs_non_current_financial_assets', id: '20', fontWeight: 700, align: 'left'},
  { type_nm: '매도가능금융자산', type: 'bs_available_for_sale_financial_assets', id: '21', fontWeight: 500, align: 'right'},
  { type_nm: '기타 장기금융상품', type: 'bs_other_non_current_financial_assets', id: '22', fontWeight: 500, align: 'right'},
  { type_nm: '유동금융부채', type: 'bs_current_financial_liabilities', id: '23', fontWeight: 700, align: 'left'},
  { type_nm: '단기차입금', type: 'bs_short_term_borrowings', id: '24', fontWeight: 500, align: 'right'},
  { type_nm: '기타 단기금융부채', type: 'bs_other_current_financial_liabilities', id: '25', fontWeight: 500, align: 'right'},
  { type_nm: '비유동금융부채', type: 'bs_non_current_financial_liabilities', id: '26', fontWeight: 700, align: 'left'},
  { type_nm: '장기차입금', type: 'bs_long_term_borrowings', id: '27', fontWeight: 500, align: 'right'},
  { type_nm: '기타 장기금융부채', type: 'bs_other_non_current_financial_liabilities', id: '28', fontWeight: 500, align: 'right'},
  { type_nm: '순금융자산', type: 'bs_net_financial_assets_liabilities', id: '29', fontWeight: 700, align: 'left'},
  { type_nm: '기타', type: 'bs_dummy', id: '30', fontWeight: 700, align: 'center'},
];


export const incomeStatementArray = [
  { type_nm: '매출액', type: 'is_revenue', id: '31', fontWeight: 700, align: 'center'},
  { type_nm: '매출원가', type: 'is_cost_of_goods_sold', id: '32', fontWeight: 500, align: 'center'},
  { type_nm: '매출액 총이익', type: 'is_gross_profit_loss', id: '33', fontWeight: 700, align: 'center'},
  { type_nm: '판매관리비', type: 'is_selling_general_cost', id: '34', fontWeight: 500, align: 'center'},
  { type_nm: '판매비', type: 'is_selling_cost', id: '35', fontWeight: 500, align: 'right'},
  { type_nm: '관리비', type: 'is_administrative_cost', id: '36', fontWeight: 500, align: 'right'},
  { type_nm: '영업이익', type: 'is_operating_profit_loss', id: '37', fontWeight: 700, align: 'center'},
  { type_nm: '기타수익', type: 'is_other_income', id: '38', fontWeight: 500, align: 'center'},
  { type_nm: '잡이익', type: 'is_other_miscellaneous_income', id: '39', fontWeight: 500, align: 'right'},
  { type_nm: '기타비용', type: 'is_other_expense', id: '40', fontWeight: 500, align: 'center'},
  { type_nm: '잡손실', type: 'is_other_miscellaneous_loss', id: '41', fontWeight: 500, align: 'right'},
  { type_nm: '기타손익', type: 'is_other_profit_loss', id: '42', fontWeight: 500, align: 'center'},
  { type_nm: '금융수익', type: 'is_financial_income', id: '43', fontWeight: 500, align: 'center'},
  { type_nm: '이자수익', type: 'is_interest_income', id: '44', fontWeight: 500, align: 'right'},
  { type_nm: '배당금수익', type: 'is_dividend_income', id: '45', fontWeight: 500, align: 'right'},
  { type_nm: '금융비용', type: 'is_financial_expense', id: '46', fontWeight: 500, align: 'center'},
  { type_nm: '이자비용', type: 'is_interest_expense', id: '47', fontWeight: 500, align: 'right'},
  { type_nm: '금융손익', type: 'is_financial_profit_loss', id: '48', fontWeight: 500, align: 'center'},
  { type_nm: '지분법이익', type: 'is_equity_method_profit', id: '49', fontWeight: 500, align: 'right'},
  { type_nm: '지분법손실', type: 'is_equity_method_loss', id: '50', fontWeight: 500, align: 'right'},
  { type_nm: '지분법손익', type: 'is_equity_method_profit_loss', id: '51', fontWeight: 500, align: 'center'},
  { type_nm: '법인세차감전 순이익', type: 'is_earnings_before_tax', id: '52', fontWeight: 700, align: 'center'},
  { type_nm: '법인세', type: 'is_income_tax_expense', id: '53', fontWeight: 500, align: 'center'},
  { type_nm: '당기순이익', type: 'is_net_income', id: '54', fontWeight: 700, align: 'center'},
  { type_nm: '비지배주주순이익', type: 'is_net_income_attributable_to_noncontrolling_shareholders', id: '55', fontWeight: 500, align: 'center'},
  { type_nm: '지배주주순이익', type: 'is_net_income_attributable_to_controlling_shareholders', id: '56', fontWeight: 700, align: 'center'},
  { type_nm: '기본 주당이익', type: 'is_basic_eps', id: '57', fontWeight: 500, align: 'center'},
  { type_nm: '희석 주당이익', type: 'is_dilluted_eps', id: '58', fontWeight: 500, align: 'center'},
  { type_nm: '계속영업이익', type: 'is_operating_profit_loss_from_continuing_operation', id: '59', fontWeight: 500, align: 'center'},
  { type_nm: '중단영업이익', type: 'is_operating_profit_loss_from_discontinued_operation', id: '60', fontWeight: 500, align: 'center'},
  { type_nm: '기타', type: 'is_dummy', id: '61', fontWeight: 500, align: 'center'},
];

// 0 - type_nm(한글 계정명), 1 - type. 2 - id, 3 - fontWeight, 4 - align
export const comprehensiveIncomeStatementArray = [
  {type_nm: '매출액', type: 'is_revenue', id: '78', fontWeight: 700, align: 'center'},
  {type_nm: '매출원가', type: 'is_cost_of_goods_sold', id: '79', fontWeight: 500, align: 'center'},
  {type_nm: '매출액 총이익', type: 'is_gross_profit_loss', id: '80', fontWeight: 700, align: 'center'},
  {type_nm: '판매관리비', type: 'is_selling_general_cost', id: '81', fontWeight: 500, align: 'center'},
  {type_nm: '판매비', type: 'is_selling_cost', id: '82', fontWeight: 500, align: 'right'},
  {type_nm: '관리비', type: 'is_administrative_cost', id: '83', fontWeight: 500, align: 'right'},
  {type_nm: '영업이익', type: 'is_operating_profit_loss', id: '84', fontWeight: 700, align: 'center'},
  {type_nm: '기타수익', type: 'is_other_income', id: '85', fontWeight: 500, align: 'center'},
  {type_nm: '잡이익', type: 'is_other_miscellaneous_income', id: '86', fontWeight: 500, align: 'right'},
  {type_nm: '기타비용', type: 'is_other_expense', id: '87', fontWeight: 500, align: 'center'},
  {type_nm: '잡손실', type: 'is_other_miscellaneous_loss', id: '88', fontWeight: 500, align: 'right'},
  {type_nm: '기타손익', type: 'is_other_profit_loss', id: '89', fontWeight: 500, align: 'center'},
  {type_nm: '금융수익', type: 'is_financial_income', id: '90', fontWeight: 500, align: 'center'},
  {type_nm: '이자수익', type: 'is_interest_income', id: '91', fontWeight: 500, align: 'right'},
  {type_nm: '배당금수익', type: 'is_dividend_income', id: '92', fontWeight: 500, align: 'right'},
  {type_nm: '금융비용', type: 'is_financial_expense', id: '93', fontWeight: 500, align: 'center'},
  {type_nm: '이자비용', type: 'is_interest_expense', id: '94', fontWeight: 500, align: 'right'},
  {type_nm: '금융손익', type: 'is_financial_profit_loss', id: '95', fontWeight: 500, align: 'center'},
  {type_nm: '지분법이익', type: 'is_equity_method_profit', id: '96', fontWeight: 500, align: 'right'},
  {type_nm: '지분법손실', type: 'is_equity_method_loss', id: '97', fontWeight: 500, align: 'right'},
  {type_nm: '지분법손익', type: 'is_equity_method_profit_loss', id: '98', fontWeight: 500, align: 'center'},
  {type_nm: '법인세차감전 순이익', type: 'is_earnings_before_tax', id: '99', fontWeight: 700, align: 'center'},
  {type_nm: '법인세', type: 'is_income_tax_expense', id: '100', fontWeight: 500, align: 'center'},
  {type_nm: '당기순이익', type: 'is_net_income', id: '101', fontWeight: 700, align: 'center'},
  {type_nm: '비지배주주순이익', type: 'is_net_income_attributable_to_noncontrolling_shareholders', id: '102', fontWeight: 500, align: 'center'},
  {type_nm: '지배주주순이익', type: 'is_net_income_attributable_to_controlling_shareholders', id: '103', fontWeight: 700, align: 'center'},
  {type_nm: '기본 주당이익', type: 'is_basic_eps', id: '104', fontWeight: 500, align: 'center'},
  {type_nm: '희석 주당이익', type: 'is_dilluted_eps', id: '105', fontWeight: 500, align: 'center'},
  {type_nm: '계속영업이익', type: 'is_operating_profit_loss_from_continuing_operation', id: '106', fontWeight: 500, align: 'center'},
  {type_nm: '중단영업이익', type: 'is_operating_profit_loss_from_discontinued_operation', id: '107', fontWeight: 500, align: 'center'},
  {type_nm: '기타', type: 'is_dummy', id: '108', fontWeight: 500, align: 'center'},
  {type_nm: '기타포괄손익', type: 'cis_other_comprehensive_income', id: '109', fontWeight: 500, align: 'center'},
  {type_nm: '총포괄손익', type: 'cis_comprehensive_income', id: '110', fontWeight: 500, align: 'center'},
  {type_nm: '포괄기타', type: 'cis_dummy', id: '111', fontWeight: 500, align: 'center'},
];


export const cashflowStatementArray = [
  {type_nm: '영업 현금', type: 'cf_operating_cash_flows', id: '65', fontWeight: 700, align: 'center'},
  {type_nm: '투자 현금', type: 'cf_investing_cash_flows', id: '66', fontWeight: 700, align: 'center'},
  {type_nm: '재무 현금', type: 'cf_financing_cash_flows', id: '67', fontWeight: 700, align: 'center'},
  {type_nm: 'NET', type: 'cf_net_cash_flows', id: '68', fontWeight: 500, align: 'center'},
  {type_nm: '기말 현금성자산', type: 'cf_end_cash_and_equivalents', id: '69', fontWeight: 700, align: 'center'},
  {type_nm: 'CAPEX', type: 'cf_total_capex', id: '70', fontWeight: 700, align: 'center'},
  {type_nm: '유형자산 취득', type: 'cf_capex_tangible', id: '71', fontWeight: 500, align: 'right'},
  {type_nm: '무형자산 취득', type: 'cf_capex_intangible', id: '72', fontWeight: 500, align: 'right'},
  {type_nm: 'FCF', type: 'cf_free_cash_flows', id: '73', fontWeight: 700, align: 'center'},
  {type_nm: '감가상각비', type: 'cf_depreciation_cost', id: '74', fontWeight: 500, align: 'center'},
  {type_nm: '유형자산상각비', type: 'cf_tangible_depreciation_cost', id: '75', fontWeight: 500, align: 'right'},
  {type_nm: '무형자산상각비', type: 'cf_intangible_amortization_cost', id: '76', fontWeight: 500, align: 'right'},
  {type_nm: '기타', type: 'cf_dummy', id: '77', fontWeight: 500, align: 'right'},
  {type_nm: '배당금지급', type: 'cf_dividend_paid', id: '113', fontWeight: 500, align: 'center'},
  {type_nm: '자기주식취득', type: 'cf_treasury_shares_acquisition', id: '114', fontWeight: 500, align: 'center'},
  {type_nm: '이자의수취', type: 'cf_interest_received', id: '115', fontWeight: 500, align: 'center'},
  {type_nm: '이자의지급', type: 'cf_interest_paid', id: '116', fontWeight: 500, align: 'center'},
];
